name: CI for Testing bash script

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [develop]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make bash script executable
        run: chmod +x generate_makefile_from_bash.sh

  generation_of_makefile:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Makefiles
        run: |
          ./generate_makefile_from_bash.sh --path Test/ONE_FILE --compile_file c --coverage y
          ./generate_makefile_from_bash.sh --path Test/MULTIPLE_FILE --compile_file c --coverage y

      - name: Upload generated Makefiles and sources
        uses: actions/upload-artifact@v4
        with:
          name: generated-code
          path: |
            Test/ONE_FILE/
            Test/MULTIPLE_FILE/

  tests:
    needs: generation_of_makefile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install lcov
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: generated-code
          path: ./Test

      - name: Run tests 
        run: |
          make -C Test/ONE_FILE clean run 
          make -C Test/MULTIPLE_FILE clean run