name : CI for Testing  bash script

on :
  push :
    branches : [master,develop]
  pull_request :
    branches : [ develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make bash script executable
        run: chmod +x generate_makefile_from_bash.sh

      - name: Install lcov
        run: |
          sudo apt update
          sudo apt install -y lcov

      - name: Run tests 
        run: |
          ./generate_makefile_from_bash.sh --path Test/ONE_FILE --compile_file c --coverage y
          ./generate_makefile_from_bash.sh --path Test/MULTIPLE_FILE --compile_file c --coverage y
          echo "List contents of Test/MULTIPLE_FILE/src:"
          ls -l Test/MULTIPLE_FILE/src || echo "src not found"
          echo "--- Show Makefile ---"
          cat Test/MULTIPLE_FILE/Makefile || echo "Makefile not found"
          echo "--- Show current directory ---"
          pwd
          tree -L 6
          make -C Test/ONE_FILE clean run 


